# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rab/sandbox/encreader

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rab/sandbox/encreader

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rab/sandbox/encreader/CMakeFiles /home/rab/sandbox/encreader/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rab/sandbox/encreader/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named edsgost

# Build rule for target.
edsgost: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edsgost
.PHONY : edsgost

# fast build rule for target.
edsgost/fast:
	$(MAKE) -f CMakeFiles/edsgost.dir/build.make CMakeFiles/edsgost.dir/build
.PHONY : edsgost/fast

#=============================================================================
# Target rules for targets named edscbc

# Build rule for target.
edscbc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edscbc
.PHONY : edscbc

# fast build rule for target.
edscbc/fast:
	$(MAKE) -f CMakeFiles/edscbc.dir/build.make CMakeFiles/edscbc.dir/build
.PHONY : edscbc/fast

#=============================================================================
# Target rules for targets named localxts

# Build rule for target.
localxts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 localxts
.PHONY : localxts

# fast build rule for target.
localxts/fast:
	$(MAKE) -f CMakeFiles/localxts.dir/build.make CMakeFiles/localxts.dir/build
.PHONY : localxts/fast

#=============================================================================
# Target rules for targets named edsaes

# Build rule for target.
edsaes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edsaes
.PHONY : edsaes

# fast build rule for target.
edsaes/fast:
	$(MAKE) -f CMakeFiles/edsaes.dir/build.make CMakeFiles/edsaes.dir/build
.PHONY : edsaes/fast

#=============================================================================
# Target rules for targets named edsctr

# Build rule for target.
edsctr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edsctr
.PHONY : edsctr

# fast build rule for target.
edsctr/fast:
	$(MAKE) -f CMakeFiles/edsctr.dir/build.make CMakeFiles/edsctr.dir/build
.PHONY : edsctr/fast

#=============================================================================
# Target rules for targets named edswhirlpool

# Build rule for target.
edswhirlpool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edswhirlpool
.PHONY : edswhirlpool

# fast build rule for target.
edswhirlpool/fast:
	$(MAKE) -f CMakeFiles/edswhirlpool.dir/build.make CMakeFiles/edswhirlpool.dir/build
.PHONY : edswhirlpool/fast

#=============================================================================
# Target rules for targets named edscfb

# Build rule for target.
edscfb: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edscfb
.PHONY : edscfb

# fast build rule for target.
edscfb/fast:
	$(MAKE) -f CMakeFiles/edscfb.dir/build.make CMakeFiles/edscfb.dir/build
.PHONY : edscfb/fast

#=============================================================================
# Target rules for targets named edsxts

# Build rule for target.
edsxts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edsxts
.PHONY : edsxts

# fast build rule for target.
edsxts/fast:
	$(MAKE) -f CMakeFiles/edsxts.dir/build.make CMakeFiles/edsxts.dir/build
.PHONY : edsxts/fast

#=============================================================================
# Target rules for targets named edsserpent

# Build rule for target.
edsserpent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edsserpent
.PHONY : edsserpent

# fast build rule for target.
edsserpent/fast:
	$(MAKE) -f CMakeFiles/edsserpent.dir/build.make CMakeFiles/edsserpent.dir/build
.PHONY : edsserpent/fast

#=============================================================================
# Target rules for targets named edstwofish

# Build rule for target.
edstwofish: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edstwofish
.PHONY : edstwofish

# fast build rule for target.
edstwofish/fast:
	$(MAKE) -f CMakeFiles/edstwofish.dir/build.make CMakeFiles/edstwofish.dir/build
.PHONY : edstwofish/fast

#=============================================================================
# Target rules for targets named edsripemd160

# Build rule for target.
edsripemd160: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 edsripemd160
.PHONY : edsripemd160

# fast build rule for target.
edsripemd160/fast:
	$(MAKE) -f CMakeFiles/edsripemd160.dir/build.make CMakeFiles/edsripemd160.dir/build
.PHONY : edsripemd160/fast

src/main/native/aes/aescrypt.o: src/main/native/aes/aescrypt.c.o

.PHONY : src/main/native/aes/aescrypt.o

# target to build an object file
src/main/native/aes/aescrypt.c.o:
	$(MAKE) -f CMakeFiles/edsaes.dir/build.make CMakeFiles/edsaes.dir/src/main/native/aes/aescrypt.c.o
.PHONY : src/main/native/aes/aescrypt.c.o

src/main/native/aes/aescrypt.i: src/main/native/aes/aescrypt.c.i

.PHONY : src/main/native/aes/aescrypt.i

# target to preprocess a source file
src/main/native/aes/aescrypt.c.i:
	$(MAKE) -f CMakeFiles/edsaes.dir/build.make CMakeFiles/edsaes.dir/src/main/native/aes/aescrypt.c.i
.PHONY : src/main/native/aes/aescrypt.c.i

src/main/native/aes/aescrypt.s: src/main/native/aes/aescrypt.c.s

.PHONY : src/main/native/aes/aescrypt.s

# target to generate assembly for a file
src/main/native/aes/aescrypt.c.s:
	$(MAKE) -f CMakeFiles/edsaes.dir/build.make CMakeFiles/edsaes.dir/src/main/native/aes/aescrypt.c.s
.PHONY : src/main/native/aes/aescrypt.c.s

src/main/native/aes/aeskey.o: src/main/native/aes/aeskey.c.o

.PHONY : src/main/native/aes/aeskey.o

# target to build an object file
src/main/native/aes/aeskey.c.o:
	$(MAKE) -f CMakeFiles/edsaes.dir/build.make CMakeFiles/edsaes.dir/src/main/native/aes/aeskey.c.o
.PHONY : src/main/native/aes/aeskey.c.o

src/main/native/aes/aeskey.i: src/main/native/aes/aeskey.c.i

.PHONY : src/main/native/aes/aeskey.i

# target to preprocess a source file
src/main/native/aes/aeskey.c.i:
	$(MAKE) -f CMakeFiles/edsaes.dir/build.make CMakeFiles/edsaes.dir/src/main/native/aes/aeskey.c.i
.PHONY : src/main/native/aes/aeskey.c.i

src/main/native/aes/aeskey.s: src/main/native/aes/aeskey.c.s

.PHONY : src/main/native/aes/aeskey.s

# target to generate assembly for a file
src/main/native/aes/aeskey.c.s:
	$(MAKE) -f CMakeFiles/edsaes.dir/build.make CMakeFiles/edsaes.dir/src/main/native/aes/aeskey.c.s
.PHONY : src/main/native/aes/aeskey.c.s

src/main/native/aes/aestab.o: src/main/native/aes/aestab.c.o

.PHONY : src/main/native/aes/aestab.o

# target to build an object file
src/main/native/aes/aestab.c.o:
	$(MAKE) -f CMakeFiles/edsaes.dir/build.make CMakeFiles/edsaes.dir/src/main/native/aes/aestab.c.o
.PHONY : src/main/native/aes/aestab.c.o

src/main/native/aes/aestab.i: src/main/native/aes/aestab.c.i

.PHONY : src/main/native/aes/aestab.i

# target to preprocess a source file
src/main/native/aes/aestab.c.i:
	$(MAKE) -f CMakeFiles/edsaes.dir/build.make CMakeFiles/edsaes.dir/src/main/native/aes/aestab.c.i
.PHONY : src/main/native/aes/aestab.c.i

src/main/native/aes/aestab.s: src/main/native/aes/aestab.c.s

.PHONY : src/main/native/aes/aestab.s

# target to generate assembly for a file
src/main/native/aes/aestab.c.s:
	$(MAKE) -f CMakeFiles/edsaes.dir/build.make CMakeFiles/edsaes.dir/src/main/native/aes/aestab.c.s
.PHONY : src/main/native/aes/aestab.c.s

src/main/native/aes/edsaes.o: src/main/native/aes/edsaes.c.o

.PHONY : src/main/native/aes/edsaes.o

# target to build an object file
src/main/native/aes/edsaes.c.o:
	$(MAKE) -f CMakeFiles/edsaes.dir/build.make CMakeFiles/edsaes.dir/src/main/native/aes/edsaes.c.o
.PHONY : src/main/native/aes/edsaes.c.o

src/main/native/aes/edsaes.i: src/main/native/aes/edsaes.c.i

.PHONY : src/main/native/aes/edsaes.i

# target to preprocess a source file
src/main/native/aes/edsaes.c.i:
	$(MAKE) -f CMakeFiles/edsaes.dir/build.make CMakeFiles/edsaes.dir/src/main/native/aes/edsaes.c.i
.PHONY : src/main/native/aes/edsaes.c.i

src/main/native/aes/edsaes.s: src/main/native/aes/edsaes.c.s

.PHONY : src/main/native/aes/edsaes.s

# target to generate assembly for a file
src/main/native/aes/edsaes.c.s:
	$(MAKE) -f CMakeFiles/edsaes.dir/build.make CMakeFiles/edsaes.dir/src/main/native/aes/edsaes.c.s
.PHONY : src/main/native/aes/edsaes.c.s

src/main/native/cbc/edscbc.o: src/main/native/cbc/edscbc.c.o

.PHONY : src/main/native/cbc/edscbc.o

# target to build an object file
src/main/native/cbc/edscbc.c.o:
	$(MAKE) -f CMakeFiles/edscbc.dir/build.make CMakeFiles/edscbc.dir/src/main/native/cbc/edscbc.c.o
.PHONY : src/main/native/cbc/edscbc.c.o

src/main/native/cbc/edscbc.i: src/main/native/cbc/edscbc.c.i

.PHONY : src/main/native/cbc/edscbc.i

# target to preprocess a source file
src/main/native/cbc/edscbc.c.i:
	$(MAKE) -f CMakeFiles/edscbc.dir/build.make CMakeFiles/edscbc.dir/src/main/native/cbc/edscbc.c.i
.PHONY : src/main/native/cbc/edscbc.c.i

src/main/native/cbc/edscbc.s: src/main/native/cbc/edscbc.c.s

.PHONY : src/main/native/cbc/edscbc.s

# target to generate assembly for a file
src/main/native/cbc/edscbc.c.s:
	$(MAKE) -f CMakeFiles/edscbc.dir/build.make CMakeFiles/edscbc.dir/src/main/native/cbc/edscbc.c.s
.PHONY : src/main/native/cbc/edscbc.c.s

src/main/native/cfb/edscfb.o: src/main/native/cfb/edscfb.c.o

.PHONY : src/main/native/cfb/edscfb.o

# target to build an object file
src/main/native/cfb/edscfb.c.o:
	$(MAKE) -f CMakeFiles/edscfb.dir/build.make CMakeFiles/edscfb.dir/src/main/native/cfb/edscfb.c.o
.PHONY : src/main/native/cfb/edscfb.c.o

src/main/native/cfb/edscfb.i: src/main/native/cfb/edscfb.c.i

.PHONY : src/main/native/cfb/edscfb.i

# target to preprocess a source file
src/main/native/cfb/edscfb.c.i:
	$(MAKE) -f CMakeFiles/edscfb.dir/build.make CMakeFiles/edscfb.dir/src/main/native/cfb/edscfb.c.i
.PHONY : src/main/native/cfb/edscfb.c.i

src/main/native/cfb/edscfb.s: src/main/native/cfb/edscfb.c.s

.PHONY : src/main/native/cfb/edscfb.s

# target to generate assembly for a file
src/main/native/cfb/edscfb.c.s:
	$(MAKE) -f CMakeFiles/edscfb.dir/build.make CMakeFiles/edscfb.dir/src/main/native/cfb/edscfb.c.s
.PHONY : src/main/native/cfb/edscfb.c.s

src/main/native/ctr/edsctr.o: src/main/native/ctr/edsctr.c.o

.PHONY : src/main/native/ctr/edsctr.o

# target to build an object file
src/main/native/ctr/edsctr.c.o:
	$(MAKE) -f CMakeFiles/edsctr.dir/build.make CMakeFiles/edsctr.dir/src/main/native/ctr/edsctr.c.o
.PHONY : src/main/native/ctr/edsctr.c.o

src/main/native/ctr/edsctr.i: src/main/native/ctr/edsctr.c.i

.PHONY : src/main/native/ctr/edsctr.i

# target to preprocess a source file
src/main/native/ctr/edsctr.c.i:
	$(MAKE) -f CMakeFiles/edsctr.dir/build.make CMakeFiles/edsctr.dir/src/main/native/ctr/edsctr.c.i
.PHONY : src/main/native/ctr/edsctr.c.i

src/main/native/ctr/edsctr.s: src/main/native/ctr/edsctr.c.s

.PHONY : src/main/native/ctr/edsctr.s

# target to generate assembly for a file
src/main/native/ctr/edsctr.c.s:
	$(MAKE) -f CMakeFiles/edsctr.dir/build.make CMakeFiles/edsctr.dir/src/main/native/ctr/edsctr.c.s
.PHONY : src/main/native/ctr/edsctr.c.s

src/main/native/gost/edsgost.o: src/main/native/gost/edsgost.c.o

.PHONY : src/main/native/gost/edsgost.o

# target to build an object file
src/main/native/gost/edsgost.c.o:
	$(MAKE) -f CMakeFiles/edsgost.dir/build.make CMakeFiles/edsgost.dir/src/main/native/gost/edsgost.c.o
.PHONY : src/main/native/gost/edsgost.c.o

src/main/native/gost/edsgost.i: src/main/native/gost/edsgost.c.i

.PHONY : src/main/native/gost/edsgost.i

# target to preprocess a source file
src/main/native/gost/edsgost.c.i:
	$(MAKE) -f CMakeFiles/edsgost.dir/build.make CMakeFiles/edsgost.dir/src/main/native/gost/edsgost.c.i
.PHONY : src/main/native/gost/edsgost.c.i

src/main/native/gost/edsgost.s: src/main/native/gost/edsgost.c.s

.PHONY : src/main/native/gost/edsgost.s

# target to generate assembly for a file
src/main/native/gost/edsgost.c.s:
	$(MAKE) -f CMakeFiles/edsgost.dir/build.make CMakeFiles/edsgost.dir/src/main/native/gost/edsgost.c.s
.PHONY : src/main/native/gost/edsgost.c.s

src/main/native/gost/gost89.o: src/main/native/gost/gost89.c.o

.PHONY : src/main/native/gost/gost89.o

# target to build an object file
src/main/native/gost/gost89.c.o:
	$(MAKE) -f CMakeFiles/edsgost.dir/build.make CMakeFiles/edsgost.dir/src/main/native/gost/gost89.c.o
.PHONY : src/main/native/gost/gost89.c.o

src/main/native/gost/gost89.i: src/main/native/gost/gost89.c.i

.PHONY : src/main/native/gost/gost89.i

# target to preprocess a source file
src/main/native/gost/gost89.c.i:
	$(MAKE) -f CMakeFiles/edsgost.dir/build.make CMakeFiles/edsgost.dir/src/main/native/gost/gost89.c.i
.PHONY : src/main/native/gost/gost89.c.i

src/main/native/gost/gost89.s: src/main/native/gost/gost89.c.s

.PHONY : src/main/native/gost/gost89.s

# target to generate assembly for a file
src/main/native/gost/gost89.c.s:
	$(MAKE) -f CMakeFiles/edsgost.dir/build.make CMakeFiles/edsgost.dir/src/main/native/gost/gost89.c.s
.PHONY : src/main/native/gost/gost89.c.s

src/main/native/localxts/localxts.o: src/main/native/localxts/localxts.c.o

.PHONY : src/main/native/localxts/localxts.o

# target to build an object file
src/main/native/localxts/localxts.c.o:
	$(MAKE) -f CMakeFiles/localxts.dir/build.make CMakeFiles/localxts.dir/src/main/native/localxts/localxts.c.o
.PHONY : src/main/native/localxts/localxts.c.o

src/main/native/localxts/localxts.i: src/main/native/localxts/localxts.c.i

.PHONY : src/main/native/localxts/localxts.i

# target to preprocess a source file
src/main/native/localxts/localxts.c.i:
	$(MAKE) -f CMakeFiles/localxts.dir/build.make CMakeFiles/localxts.dir/src/main/native/localxts/localxts.c.i
.PHONY : src/main/native/localxts/localxts.c.i

src/main/native/localxts/localxts.s: src/main/native/localxts/localxts.c.s

.PHONY : src/main/native/localxts/localxts.s

# target to generate assembly for a file
src/main/native/localxts/localxts.c.s:
	$(MAKE) -f CMakeFiles/localxts.dir/build.make CMakeFiles/localxts.dir/src/main/native/localxts/localxts.c.s
.PHONY : src/main/native/localxts/localxts.c.s

src/main/native/ripemd160/edsripemd160.o: src/main/native/ripemd160/edsripemd160.c.o

.PHONY : src/main/native/ripemd160/edsripemd160.o

# target to build an object file
src/main/native/ripemd160/edsripemd160.c.o:
	$(MAKE) -f CMakeFiles/edsripemd160.dir/build.make CMakeFiles/edsripemd160.dir/src/main/native/ripemd160/edsripemd160.c.o
.PHONY : src/main/native/ripemd160/edsripemd160.c.o

src/main/native/ripemd160/edsripemd160.i: src/main/native/ripemd160/edsripemd160.c.i

.PHONY : src/main/native/ripemd160/edsripemd160.i

# target to preprocess a source file
src/main/native/ripemd160/edsripemd160.c.i:
	$(MAKE) -f CMakeFiles/edsripemd160.dir/build.make CMakeFiles/edsripemd160.dir/src/main/native/ripemd160/edsripemd160.c.i
.PHONY : src/main/native/ripemd160/edsripemd160.c.i

src/main/native/ripemd160/edsripemd160.s: src/main/native/ripemd160/edsripemd160.c.s

.PHONY : src/main/native/ripemd160/edsripemd160.s

# target to generate assembly for a file
src/main/native/ripemd160/edsripemd160.c.s:
	$(MAKE) -f CMakeFiles/edsripemd160.dir/build.make CMakeFiles/edsripemd160.dir/src/main/native/ripemd160/edsripemd160.c.s
.PHONY : src/main/native/ripemd160/edsripemd160.c.s

src/main/native/serpent/edsserpent.o: src/main/native/serpent/edsserpent.c.o

.PHONY : src/main/native/serpent/edsserpent.o

# target to build an object file
src/main/native/serpent/edsserpent.c.o:
	$(MAKE) -f CMakeFiles/edsserpent.dir/build.make CMakeFiles/edsserpent.dir/src/main/native/serpent/edsserpent.c.o
.PHONY : src/main/native/serpent/edsserpent.c.o

src/main/native/serpent/edsserpent.i: src/main/native/serpent/edsserpent.c.i

.PHONY : src/main/native/serpent/edsserpent.i

# target to preprocess a source file
src/main/native/serpent/edsserpent.c.i:
	$(MAKE) -f CMakeFiles/edsserpent.dir/build.make CMakeFiles/edsserpent.dir/src/main/native/serpent/edsserpent.c.i
.PHONY : src/main/native/serpent/edsserpent.c.i

src/main/native/serpent/edsserpent.s: src/main/native/serpent/edsserpent.c.s

.PHONY : src/main/native/serpent/edsserpent.s

# target to generate assembly for a file
src/main/native/serpent/edsserpent.c.s:
	$(MAKE) -f CMakeFiles/edsserpent.dir/build.make CMakeFiles/edsserpent.dir/src/main/native/serpent/edsserpent.c.s
.PHONY : src/main/native/serpent/edsserpent.c.s

src/main/native/serpent/serpent.o: src/main/native/serpent/serpent.c.o

.PHONY : src/main/native/serpent/serpent.o

# target to build an object file
src/main/native/serpent/serpent.c.o:
	$(MAKE) -f CMakeFiles/edsserpent.dir/build.make CMakeFiles/edsserpent.dir/src/main/native/serpent/serpent.c.o
.PHONY : src/main/native/serpent/serpent.c.o

src/main/native/serpent/serpent.i: src/main/native/serpent/serpent.c.i

.PHONY : src/main/native/serpent/serpent.i

# target to preprocess a source file
src/main/native/serpent/serpent.c.i:
	$(MAKE) -f CMakeFiles/edsserpent.dir/build.make CMakeFiles/edsserpent.dir/src/main/native/serpent/serpent.c.i
.PHONY : src/main/native/serpent/serpent.c.i

src/main/native/serpent/serpent.s: src/main/native/serpent/serpent.c.s

.PHONY : src/main/native/serpent/serpent.s

# target to generate assembly for a file
src/main/native/serpent/serpent.c.s:
	$(MAKE) -f CMakeFiles/edsserpent.dir/build.make CMakeFiles/edsserpent.dir/src/main/native/serpent/serpent.c.s
.PHONY : src/main/native/serpent/serpent.c.s

src/main/native/twofish/edstwofish.o: src/main/native/twofish/edstwofish.c.o

.PHONY : src/main/native/twofish/edstwofish.o

# target to build an object file
src/main/native/twofish/edstwofish.c.o:
	$(MAKE) -f CMakeFiles/edstwofish.dir/build.make CMakeFiles/edstwofish.dir/src/main/native/twofish/edstwofish.c.o
.PHONY : src/main/native/twofish/edstwofish.c.o

src/main/native/twofish/edstwofish.i: src/main/native/twofish/edstwofish.c.i

.PHONY : src/main/native/twofish/edstwofish.i

# target to preprocess a source file
src/main/native/twofish/edstwofish.c.i:
	$(MAKE) -f CMakeFiles/edstwofish.dir/build.make CMakeFiles/edstwofish.dir/src/main/native/twofish/edstwofish.c.i
.PHONY : src/main/native/twofish/edstwofish.c.i

src/main/native/twofish/edstwofish.s: src/main/native/twofish/edstwofish.c.s

.PHONY : src/main/native/twofish/edstwofish.s

# target to generate assembly for a file
src/main/native/twofish/edstwofish.c.s:
	$(MAKE) -f CMakeFiles/edstwofish.dir/build.make CMakeFiles/edstwofish.dir/src/main/native/twofish/edstwofish.c.s
.PHONY : src/main/native/twofish/edstwofish.c.s

src/main/native/twofish/twofish.o: src/main/native/twofish/twofish.c.o

.PHONY : src/main/native/twofish/twofish.o

# target to build an object file
src/main/native/twofish/twofish.c.o:
	$(MAKE) -f CMakeFiles/edstwofish.dir/build.make CMakeFiles/edstwofish.dir/src/main/native/twofish/twofish.c.o
.PHONY : src/main/native/twofish/twofish.c.o

src/main/native/twofish/twofish.i: src/main/native/twofish/twofish.c.i

.PHONY : src/main/native/twofish/twofish.i

# target to preprocess a source file
src/main/native/twofish/twofish.c.i:
	$(MAKE) -f CMakeFiles/edstwofish.dir/build.make CMakeFiles/edstwofish.dir/src/main/native/twofish/twofish.c.i
.PHONY : src/main/native/twofish/twofish.c.i

src/main/native/twofish/twofish.s: src/main/native/twofish/twofish.c.s

.PHONY : src/main/native/twofish/twofish.s

# target to generate assembly for a file
src/main/native/twofish/twofish.c.s:
	$(MAKE) -f CMakeFiles/edstwofish.dir/build.make CMakeFiles/edstwofish.dir/src/main/native/twofish/twofish.c.s
.PHONY : src/main/native/twofish/twofish.c.s

src/main/native/whirlpool/edswhirlpool.o: src/main/native/whirlpool/edswhirlpool.c.o

.PHONY : src/main/native/whirlpool/edswhirlpool.o

# target to build an object file
src/main/native/whirlpool/edswhirlpool.c.o:
	$(MAKE) -f CMakeFiles/edswhirlpool.dir/build.make CMakeFiles/edswhirlpool.dir/src/main/native/whirlpool/edswhirlpool.c.o
.PHONY : src/main/native/whirlpool/edswhirlpool.c.o

src/main/native/whirlpool/edswhirlpool.i: src/main/native/whirlpool/edswhirlpool.c.i

.PHONY : src/main/native/whirlpool/edswhirlpool.i

# target to preprocess a source file
src/main/native/whirlpool/edswhirlpool.c.i:
	$(MAKE) -f CMakeFiles/edswhirlpool.dir/build.make CMakeFiles/edswhirlpool.dir/src/main/native/whirlpool/edswhirlpool.c.i
.PHONY : src/main/native/whirlpool/edswhirlpool.c.i

src/main/native/whirlpool/edswhirlpool.s: src/main/native/whirlpool/edswhirlpool.c.s

.PHONY : src/main/native/whirlpool/edswhirlpool.s

# target to generate assembly for a file
src/main/native/whirlpool/edswhirlpool.c.s:
	$(MAKE) -f CMakeFiles/edswhirlpool.dir/build.make CMakeFiles/edswhirlpool.dir/src/main/native/whirlpool/edswhirlpool.c.s
.PHONY : src/main/native/whirlpool/edswhirlpool.c.s

src/main/native/whirlpool/whirlpool.o: src/main/native/whirlpool/whirlpool.c.o

.PHONY : src/main/native/whirlpool/whirlpool.o

# target to build an object file
src/main/native/whirlpool/whirlpool.c.o:
	$(MAKE) -f CMakeFiles/edswhirlpool.dir/build.make CMakeFiles/edswhirlpool.dir/src/main/native/whirlpool/whirlpool.c.o
.PHONY : src/main/native/whirlpool/whirlpool.c.o

src/main/native/whirlpool/whirlpool.i: src/main/native/whirlpool/whirlpool.c.i

.PHONY : src/main/native/whirlpool/whirlpool.i

# target to preprocess a source file
src/main/native/whirlpool/whirlpool.c.i:
	$(MAKE) -f CMakeFiles/edswhirlpool.dir/build.make CMakeFiles/edswhirlpool.dir/src/main/native/whirlpool/whirlpool.c.i
.PHONY : src/main/native/whirlpool/whirlpool.c.i

src/main/native/whirlpool/whirlpool.s: src/main/native/whirlpool/whirlpool.c.s

.PHONY : src/main/native/whirlpool/whirlpool.s

# target to generate assembly for a file
src/main/native/whirlpool/whirlpool.c.s:
	$(MAKE) -f CMakeFiles/edswhirlpool.dir/build.make CMakeFiles/edswhirlpool.dir/src/main/native/whirlpool/whirlpool.c.s
.PHONY : src/main/native/whirlpool/whirlpool.c.s

src/main/native/xts/edsxts.o: src/main/native/xts/edsxts.c.o

.PHONY : src/main/native/xts/edsxts.o

# target to build an object file
src/main/native/xts/edsxts.c.o:
	$(MAKE) -f CMakeFiles/edsxts.dir/build.make CMakeFiles/edsxts.dir/src/main/native/xts/edsxts.c.o
.PHONY : src/main/native/xts/edsxts.c.o

src/main/native/xts/edsxts.i: src/main/native/xts/edsxts.c.i

.PHONY : src/main/native/xts/edsxts.i

# target to preprocess a source file
src/main/native/xts/edsxts.c.i:
	$(MAKE) -f CMakeFiles/edsxts.dir/build.make CMakeFiles/edsxts.dir/src/main/native/xts/edsxts.c.i
.PHONY : src/main/native/xts/edsxts.c.i

src/main/native/xts/edsxts.s: src/main/native/xts/edsxts.c.s

.PHONY : src/main/native/xts/edsxts.s

# target to generate assembly for a file
src/main/native/xts/edsxts.c.s:
	$(MAKE) -f CMakeFiles/edsxts.dir/build.make CMakeFiles/edsxts.dir/src/main/native/xts/edsxts.c.s
.PHONY : src/main/native/xts/edsxts.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... edsgost"
	@echo "... edscbc"
	@echo "... localxts"
	@echo "... edsaes"
	@echo "... edsctr"
	@echo "... edswhirlpool"
	@echo "... edscfb"
	@echo "... edsxts"
	@echo "... edsserpent"
	@echo "... edstwofish"
	@echo "... edsripemd160"
	@echo "... src/main/native/aes/aescrypt.o"
	@echo "... src/main/native/aes/aescrypt.i"
	@echo "... src/main/native/aes/aescrypt.s"
	@echo "... src/main/native/aes/aeskey.o"
	@echo "... src/main/native/aes/aeskey.i"
	@echo "... src/main/native/aes/aeskey.s"
	@echo "... src/main/native/aes/aestab.o"
	@echo "... src/main/native/aes/aestab.i"
	@echo "... src/main/native/aes/aestab.s"
	@echo "... src/main/native/aes/edsaes.o"
	@echo "... src/main/native/aes/edsaes.i"
	@echo "... src/main/native/aes/edsaes.s"
	@echo "... src/main/native/cbc/edscbc.o"
	@echo "... src/main/native/cbc/edscbc.i"
	@echo "... src/main/native/cbc/edscbc.s"
	@echo "... src/main/native/cfb/edscfb.o"
	@echo "... src/main/native/cfb/edscfb.i"
	@echo "... src/main/native/cfb/edscfb.s"
	@echo "... src/main/native/ctr/edsctr.o"
	@echo "... src/main/native/ctr/edsctr.i"
	@echo "... src/main/native/ctr/edsctr.s"
	@echo "... src/main/native/gost/edsgost.o"
	@echo "... src/main/native/gost/edsgost.i"
	@echo "... src/main/native/gost/edsgost.s"
	@echo "... src/main/native/gost/gost89.o"
	@echo "... src/main/native/gost/gost89.i"
	@echo "... src/main/native/gost/gost89.s"
	@echo "... src/main/native/localxts/localxts.o"
	@echo "... src/main/native/localxts/localxts.i"
	@echo "... src/main/native/localxts/localxts.s"
	@echo "... src/main/native/ripemd160/edsripemd160.o"
	@echo "... src/main/native/ripemd160/edsripemd160.i"
	@echo "... src/main/native/ripemd160/edsripemd160.s"
	@echo "... src/main/native/serpent/edsserpent.o"
	@echo "... src/main/native/serpent/edsserpent.i"
	@echo "... src/main/native/serpent/edsserpent.s"
	@echo "... src/main/native/serpent/serpent.o"
	@echo "... src/main/native/serpent/serpent.i"
	@echo "... src/main/native/serpent/serpent.s"
	@echo "... src/main/native/twofish/edstwofish.o"
	@echo "... src/main/native/twofish/edstwofish.i"
	@echo "... src/main/native/twofish/edstwofish.s"
	@echo "... src/main/native/twofish/twofish.o"
	@echo "... src/main/native/twofish/twofish.i"
	@echo "... src/main/native/twofish/twofish.s"
	@echo "... src/main/native/whirlpool/edswhirlpool.o"
	@echo "... src/main/native/whirlpool/edswhirlpool.i"
	@echo "... src/main/native/whirlpool/edswhirlpool.s"
	@echo "... src/main/native/whirlpool/whirlpool.o"
	@echo "... src/main/native/whirlpool/whirlpool.i"
	@echo "... src/main/native/whirlpool/whirlpool.s"
	@echo "... src/main/native/xts/edsxts.o"
	@echo "... src/main/native/xts/edsxts.i"
	@echo "... src/main/native/xts/edsxts.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

